import {
  Controller,
  Post,
  Delete,
  Body,
  Param,
  HttpCode,
  HttpStatus,
  BadRequestException,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiBody,
  ApiParam,
  ApiCreatedResponse,
  ApiOkResponse,
  ApiBadRequestResponse,
  ApiNotFoundResponse,
  ApiConflictResponse,
  ApiExtraModels,
  getSchemaPath,
} from '@nestjs/swagger';
import { BookingsService } from './bookings.service.js';
import { CreateBookingDto } from './dto/create-booking.dto.js';
import {
  BookingResponse,
  BookingDto,
  ErrorResponse,
} from '../common/swagger/api-schemas.js';
import { validate as isUuid } from 'uuid';

@ApiTags('Bookings')
@ApiExtraModels(BookingResponse, BookingDto, ErrorResponse)
@Controller('bookings')
export class BookingsController {
  constructor(private readonly bookingsService: BookingsService) {}

  // ── POST /bookings ────────────────────────────────────────────────────────
  @Post()
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({
    summary: 'Create a booking',
    description:
      'Books an available slot for a customer. ' +
      '`customerName` and `customerEmail` are trimmed before validation. ' +
      'The booking `id` is generated by the database. ' +
      'If two concurrent requests target the same slot, exactly one will succeed (201) ' +
      'and the other will receive 409. No authentication required.',
  })
  @ApiBody({ type: CreateBookingDto })
  @ApiCreatedResponse({
    description: 'Booking created successfully.',
    schema: { $ref: getSchemaPath(BookingResponse) },
    content: {
      'application/json': {
        example: {
          booking: {
            id: 'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d',
            slotId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
            customerName: 'Alice Smith',
            customerEmail: 'alice@example.com',
            status: 'active',
          },
        },
      },
    },
  })
  @ApiBadRequestResponse({
    description:
      '`VALIDATION_ERROR` — one or more fields failed validation, or the request body is malformed JSON. ' +
      'Possible reasons: `slotId` is not a valid UUID v4; `customerName` is empty after trimming; ' +
      '`customerEmail` is not a valid email address.',
    schema: { $ref: getSchemaPath(ErrorResponse) },
    content: {
      'application/json': {
        examples: {
          invalidUuid: {
            summary: 'Invalid slotId',
            value: { error: { code: 'VALIDATION_ERROR', message: 'slotId must be a valid UUID' } },
          },
          emptyName: {
            summary: 'Empty customerName',
            value: { error: { code: 'VALIDATION_ERROR', message: 'customerName must not be empty' } },
          },
          invalidEmail: {
            summary: 'Invalid customerEmail',
            value: { error: { code: 'VALIDATION_ERROR', message: 'customerEmail must be a valid email' } },
          },
          malformedJson: {
            summary: 'Malformed JSON body',
            value: { error: { code: 'VALIDATION_ERROR', message: 'Malformed JSON in request body.' } },
          },
        },
      },
    },
  })
  @ApiNotFoundResponse({
    description: '`SLOT_NOT_FOUND` — no slot exists with the given `slotId`.',
    schema: { $ref: getSchemaPath(ErrorResponse) },
    content: {
      'application/json': {
        example: { error: { code: 'SLOT_NOT_FOUND', message: 'Slot not found.' } },
      },
    },
  })
  @ApiConflictResponse({
    description:
      '`SLOT_UNAVAILABLE` — the slot already has an active booking. ' +
      'Enforced by a database partial unique index (`WHERE status = \'active\'`), ' +
      'guaranteeing safety under concurrent requests.',
    schema: { $ref: getSchemaPath(ErrorResponse) },
    content: {
      'application/json': {
        example: { error: { code: 'SLOT_UNAVAILABLE', message: 'This slot already has an active booking.' } },
      },
    },
  })
  createBooking(@Body() dto: CreateBookingDto) {
    return this.bookingsService.createBooking(dto);
  }

  // ── DELETE /bookings/:bookingId ───────────────────────────────────────────
  @Delete(':bookingId')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Cancel a booking',
    description:
      'Changes an **active** booking\'s status to `cancelled`, making its slot available again. ' +
      'The booking record is kept in the database. ' +
      '**Idempotent:** calling this on an already-cancelled booking returns the same ' +
      '`cancelled` booking with 200 — no further changes are made and no event is emitted. ' +
      'Cancelling an old cancelled booking does **not** affect any newer active booking for the same slot. ' +
      'No authentication required.',
  })
  @ApiParam({
    name: 'bookingId',
    description: 'UUID v4 of the booking to cancel.',
    example: 'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d',
    schema: { type: 'string', format: 'uuid' },
  })
  @ApiOkResponse({
    description: 'Booking cancelled (or was already cancelled).',
    schema: { $ref: getSchemaPath(BookingResponse) },
    content: {
      'application/json': {
        examples: {
          justCancelled: {
            summary: 'Booking just cancelled',
            value: {
              booking: {
                id: 'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d',
                slotId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
                customerName: 'Alice Smith',
                customerEmail: 'alice@example.com',
                status: 'cancelled',
              },
            },
          },
          alreadyCancelled: {
            summary: 'Repeated cancellation (idempotent)',
            value: {
              booking: {
                id: 'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d',
                slotId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
                customerName: 'Alice Smith',
                customerEmail: 'alice@example.com',
                status: 'cancelled',
              },
            },
          },
        },
      },
    },
  })
  @ApiBadRequestResponse({
    description: '`VALIDATION_ERROR` — `bookingId` is not a valid UUID v4.',
    schema: { $ref: getSchemaPath(ErrorResponse) },
    content: {
      'application/json': {
        example: { error: { code: 'VALIDATION_ERROR', message: 'bookingId must be a valid UUID.' } },
      },
    },
  })
  @ApiNotFoundResponse({
    description: '`BOOKING_NOT_FOUND` — no booking exists with the given `bookingId`.',
    schema: { $ref: getSchemaPath(ErrorResponse) },
    content: {
      'application/json': {
        example: { error: { code: 'BOOKING_NOT_FOUND', message: 'Booking not found.' } },
      },
    },
  })
  cancelBooking(@Param('bookingId') bookingId: string) {
    if (!isUuid(bookingId)) {
      throw new BadRequestException({
        error: {
          code: 'VALIDATION_ERROR',
          message: 'bookingId must be a valid UUID.',
        },
      });
    }
    return this.bookingsService.cancelBooking(bookingId);
  }
}
