import { ApiProperty } from '@nestjs/swagger';

// ── Shared error shape ──────────────────────────────────────────────────────

export class ErrorDetail {
  @ApiProperty({ example: 'VALIDATION_ERROR' })
  code: string;

  @ApiProperty({ example: 'slotId must be a valid UUID.' })
  message: string;
}

export class ErrorResponse {
  @ApiProperty({ type: ErrorDetail })
  error: ErrorDetail;
}

// ── Slot ────────────────────────────────────────────────────────────────────

export class SlotDto {
  @ApiProperty({
    example: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
    description: 'Unique slot identifier (UUID v4)',
  })
  id: string;

  @ApiProperty({
    example: '2030-01-15T09:00:00.000Z',
    description: 'Slot start time (ISO 8601, UTC)',
  })
  startsAt: string;

  @ApiProperty({
    example: '2030-01-15T09:30:00.000Z',
    description: 'Slot end time (ISO 8601, UTC)',
  })
  endsAt: string;
}

export class SlotsResponse {
  @ApiProperty({ type: [SlotDto] })
  slots: SlotDto[];
}

// ── Booking ─────────────────────────────────────────────────────────────────

export class BookingDto {
  @ApiProperty({
    example: 'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d',
    description: 'Unique booking identifier (UUID v4, generated by the database)',
  })
  id: string;

  @ApiProperty({
    example: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
    description: 'The slot that was booked',
  })
  slotId: string;

  @ApiProperty({ example: 'Alice Smith' })
  customerName: string;

  @ApiProperty({ example: 'alice@example.com' })
  customerEmail: string;

  @ApiProperty({
    enum: ['active', 'cancelled'],
    example: 'active',
    description: 'Booking status',
  })
  status: string;
}

export class BookingResponse {
  @ApiProperty({ type: BookingDto })
  booking: BookingDto;
}
